# fly.toml app configuration file generated for telegram-weather on 2023-05-07T09:58:29-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "telegram-weather"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1m"
    interval = "15s"
    timeout = "5s"

  [[services.http_checks]]
    endpoint = "/health"
    interval = "15s"
    timeout = "5s"
    grace_period = "1m"
    tls_skip_verify = false