# fly.toml app configuration file generated for telegram-weather on 2023-05-07T09:58:29-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "telegram-weather"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true